/*
 * This source file was generated by the Gradle 'init' task
 */
package org.devops;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class MainTest {
    @Test
    void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertThat(classUnderTest.getGreeting()).isNotNull();
        assertThat(classUnderTest.getGreeting()).isEqualTo("Hello World!");
    }
}
